# Generated by Django 3.0.4 on 2022-02-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Verification code')),
                ('email', models.CharField(max_length=35, verbose_name='Email')),
                ('send_type', models.CharField(choices=[('register', 'register'), ('forget', 'forget')], default='register', max_length=20)),
            ],
            options={
                'verbose_name': 'Verification code',
                'verbose_name_plural': 'Verification codes',
            },
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Info', 'verbose_name_plural': 'User Info'},
        ),
    ]
